# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = com.github.game_gpt
pluginName = Gnostic Code
# SemVer format -> https://semver.org
pluginVersion = 0.0.0
pluginRepositoryUrl = https://github.com/oovm/intellij-gnostic



# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# for insight into build numbers and IntelliJ Platform versions.
pluginSinceBuild = 231

# Java language level used to compile sources
# Java 17 is required since IntelliJ 2022.2
javaVersion = 17

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.4.0
org.gradle.caching = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
org.gradle.daemon = true

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
kotlin.daemon.jvmargs = -Xmx8G
